### ISSUE TITLE
Error in setup (again)

### ISSUE THREAD

**Issue by jasonmold** [srodney/sndrizpipe#13]
Hi, 

I updated the pipeline and it stopped working. I tried to reinstall it again but setup fails miserably. This is what I did: 

git pull  https://github.com/srodney/sndrizpipe.git
python setup.py install         --- I also tried develop wit no success 

Traceback (most recent call last):
  File "setup.py", line 85, in <module>
    get_debug_option(PACKAGENAME))
  File "/Users/jason/software/sndrizpipe/astropy_helpers/astropy_helpers/version_helpers.py", line 231, in generate_version_py
    version_module = get_pkg_version_module(packagename)
  File "/Users/jason/software/sndrizpipe/astropy_helpers/astropy_helpers/version_helpers.py", line 302, in get_pkg_version_module
    return __import__(packagename + '.version', fromlist=[''])
  File "/Users/jason/software/sndrizpipe/sndrizpipe/__init__.py", line 11, in <module>
    from . import drizzle
  File "/Users/jason/software/sndrizpipe/sndrizpipe/drizzle.py", line 8, in <module>
    from drizzlepac import astrodrizzle
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/drizzlepac/__init__.py", line 66, in <module>
    from . import alignimages
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/drizzlepac/alignimages.py", line 29, in <module>
    from drizzlepac.hlautils import astrometric_utils as amutils
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/drizzlepac/hlautils/astrometric_utils.py", line 43, in <module>
    from astropy.visualization import SqrtStretch
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/astropy/visualization/__init__.py", line 6, in <module>
    from .mpl_style import *
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/astropy/visualization/mpl_style.py", line 10, in <module>
    MATPLOTLIB_GE_1_5 = minversion('matplotlib', '1.5')
  File "/Users/jason/anaconda2/envs/astroconda/lib/python3.7/site-packages/astropy/utils/introspection.py", line 140, in minversion
    have_version = getattr(module, version_path)
AttributeError: module 'matplotlib' has no attribute '__version__'

**Comment by jasonmold** [comment]
This was solved by uninstalling and then reinstalling matplotlib:

pip uninstall matplotlib
pip install marplotlib 
python setup.py install
